name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Registry login
    - name: Login to Docker Registry
      run: echo "${DOCKER_REGISTRY_PASSWORD}" | docker login -u "${DOCKER_REGISTRY_USERNAME}" --password-stdin ${DOCKER_REGISTRY_URL}
    
    # Publish paper-consumption
    - name: Build and Push paper-consumption
      run: |
        docker build -t robbelouwet/paper-consumption -f paper-docker-consumption/Dockerfile
        docker push robbelouwet/paper-consumption
    
    # Publish paper-dedicated
    - name: Build and Push paper-dedicated
      run: |
        docker build -t robbelouwet/paper-dedicated -f paper-docker-dedicated/Dockerfile
        docker push robbelouwet/paper-dedicated
        
    # Publish velocity-dedicated
    - name: Build and Push velocity-dedicated
      run: |
        docker build -t robbelouwet/velocity-dedicated -f velocity-docker/Dockerfile
        docker push robbelouwet/velocity-dedicated
