name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Registry login
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    
    # Publish paper-consumption
    - name: Build and Push paper-consumption
      run: |
        docker build -t robbelouwet/paper-consumption paper-docker-consumption
        docker push robbelouwet/paper-consumption
    
    # Publish paper-dedicated, have root as build dir to include cerrts etc.
    - name: Build and Push paper-dedicated
      run: |
        docker build -f paper-docker-dedicate/Dockerfile -t robbelouwet/paper-dedicated .
        docker push robbelouwet/paper-dedicated

    # Publish paper-dedicated, have root as build dir to include certs etc.
    - name: Build and Push bedrock-dedicated
      run: |
        docker build -f bedrock-dedicated/Dockerfile -t robbelouwet/bedrock-dedicated .
        docker push robbelouwet/bedrock-dedicated
        


